version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/viewflow-crece/
hooks:
  AfterInstall:
   - location: creceEcuador/install_app_dependencies.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: creceEcuador/start_server.sh
     timeout: 300
     runas: root
