name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted 
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.6.x']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r creceEcuador/requirements.txt
    - name: Run Tests
      run: |
        python creceEcuador/manage.py test
